### ISSUE TITLE
Provide Manifest file with options to configure it from the backend

### ISSUE THREAD

**Issue by toh82** [meanbee/magento-meanbee-pwa#10]
Let's provide a pwa manifest file which is configurable from the magento backend.
This is the information about the manifest file:  
https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/

It should be checked which parts can be filled with existing information and which parts have to be configured.

**Comment by bobbyshaw** [comment]
Relevant: https://github.com/meanbee/magento2-webappmanifest

**Comment by andrewhowdencom** [comment]
Here, meanbee have previously used the merged config.xml: https://github.com/meanbee/magento2-webappmanifest/blob/master/src/etc/config.xml#L4-L12 

Additionally, display type seems to be configurable inadmin: https://github.com/meanbee/magento2-webappmanifest/blob/master/src/Model/Config/Source/Displaytype.php

As does orientation: https://github.com/meanbee/magento2-webappmanifest/blob/master/src/Model/Config/Source/Orientation.php

Full list of configurable options (I think): https://github.com/meanbee/magento2-webappmanifest/blob/master/src/Model/Manifest.php#L11-L20

Suggest we basically reimplement this on M1. It seems that the design is good, and doing it any other way than what's been done previously doesn't seem like a good idea. 

@bobbyshaw @tgerulaitis originally we had talked about contributing this back to this extension, but you've previously separated out manifest.json and the m2-pwa. Do you consider it a superior approach to leave it similarly separate for M1?

**Comment by tgerulaitis** [comment]
I don't mind either way. M2 has the advantage of using Composer, which makes it much easier to pull in a number of small packages as dependencies. In M1 it's much more common to bundle related functionality in a single package. Since the app manifest doesn't conflict with a service worker (and rarely will be used without it), I'm happy with bundling it in, as long as we have a System Configuration option to turn it off should we need to.

**Comment by andrewhowdencom** [comment]
I might vote to keep them separate still; with the cotya/magento-composer-installer stuff it's super easy to get started with that, and I don't have heaps of interest in supporting non-composer projects as first class citizens. We can generate a package for m1 if it's requiredd, add it to the `releases` section.

**Comment by andrewhowdencom** [comment]
Progress can be tracked here: https://github.com/sitewards/magento-webappmanifest

**Comment by andrewhowdencom** [comment]
This is pretty close to being tagged 1.0. I suggest closing this issue noww
