### ISSUE TITLE
Manifest.json

### ISSUE THREAD

**Issue by MLisiecki** [meanbee/magento-meanbee-pwa#13]
Hi,

is it possible to create manifest.json? 
https://developers.google.com/web/tools/chrome-devtools/progressive-web-apps#manifest

Regards 👍

**Comment by bobbyshaw** [comment]
Hi @MLisiecki, this has been raised in another issue and @andrewhowdencom has offered to work on it: https://github.com/meanbee/magento-meanbee-pwa/issues/10#issuecomment-311600994

**Comment by andrewhowdencom** [comment]
It's slow work ;) bit you can see it in progress at github.com/sitewards/magento-webappmanifest. We set aside an hour a week to chip away on it a bit. It was actually @toh82's idea I think, or @PatrickKubica.
