### ISSUE TITLE
index.html visitors in google analytics

### ISSUE THREAD

**Issue by HRR1337** [meanbee/magento-meanbee-pwa#23]
Hi there.

Since the install on the live site, we see now also users on 'index.html' page. Has that to do with PWA?

Thanks!

**Comment by tgerulaitis** [comment]
Hi @HRR1337 ,

Nope, there's nothing that directs people to `index.html` in the extension itself. The service worker in the extension simply caches whatever page and assets the visitors request. If visitors have no network connection and visit a page they haven't visited before (it's not cached), the service worker shows a pre-cached version of the offline page (by default, after you install the extension, a CMS page with the identifier `offline` is created, but it can be changed).

I would have a look at your web server logs and try to capture the "Referer" header for people requesting the `index.html` page. This will show you where they're coming from and will hopefully point you to the right page (or service!) that's redirecting people to this route.

**Comment by HRR1337** [comment]
Havent seen this behaviour since. Close this issue.
