### ISSUE TITLE
amp pwa

### ISSUE THREAD

**Issue by ankit4794** [meanbee/magento-meanbee-pwa#4]
how to add resgister.phtml page in amp module?

<"amp-install-serviceworker" src="pwa/serviceworker/serviceworker.js" data-iframe-src="pwa/serviceworker/register.phtml" layout="nodisplay" style="display: none;">
</"amp-install-serviceworker">

does it work?

**Comment by tgerulaitis** [comment]
Unfortunately, we haven't tested this service worker in AMP, but it doesn't use anything non-standard for service workers, so it should work.

Looking at the AMP documentation, looks like you don't need a registration script to register a service worker. Can do that with just:
```
<amp-install-serviceworker src="/serviceworker.js" layout="nodisplay>
</amp-install-serviceworker>
```

However, that's only going to load the service worker when the AMP page is served from origin. To make it load from AMP cache, you'll have to create your own controller action with a layout that only includes the `register.phtml` block and then use it for the `data-iframe-src` attribute like this:
```
<amp-install-serviceworker
    src="/serviceworker.js"
    data-iframe-src="/my-custom-frontname/controller/action"
    layout="nodisplay>
</amp-install-serviceworker>
```

**Comment by ankit4794** [comment]
after loading got this error..

"Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html')."

**Comment by tgerulaitis** [comment]
Sounds like something is either wrong with the `/serviceworker.js` URL or the configuration. The service worker controller should be setting the content type to `text/javascript`. What do you get if you visit the `/serviceworker.js` URL directly?
