### ISSUE TITLE
Service worker registration file? 

### ISSUE THREAD

**Issue by alwaysriding1** [meanbee/magento-meanbee-pwa#5]
Hi Guys,

Added this at: alwaysriding.co.uk (cycling site)

And getting in source code:

console.log('Service worker registration failed:',err);

Any idea what we might be doing wrong?

Pete

**Comment by bobbyshaw** [comment]
What Browser/OS version are you using?
The service worker is working correctly on your site for me! :)

<img width="1436" alt="screen shot 2017-03-10 at 19 56 35" src="https://cloud.githubusercontent.com/assets/553566/23810963/c75b330e-05cb-11e7-8cb5-b63117e65aa4.png">

**Comment by alwaysriding1** [comment]
Ah ok, thanks - I’m on Chrome - Version 56.0.2924.87 (64-bit)

It just said in the source code that the service work had an issue, and that combined with the fact that the site shoes the dinosaur on viewed pages once I turn wifi off made me think we had an issue!

Pete

**Comment by bobbyshaw** [comment]
Not sure why it didn't register for you. It registered fine for me and is working offline:

<img width="1440" alt="screen shot 2017-03-11 at 15 16 45" src="https://cloud.githubusercontent.com/assets/553566/23824547/6db83f90-0670-11e7-9668-16f5579009f1.png">

**Comment by alwaysriding1** [comment]
Well that's good news! 

Yes on my iPhone on chrome browser it does not seem to work as I had hoped - dinosaur appears if you turn to airplane mode. But desktop seems better. 

Many thanks for working and bringing out this little app, I'll follow its progress and install any updates as you provide them. 

Pete

**Comment by alwaysriding1** [comment]
Sorry Tom, I see it only works on Android not iOS and I was checking on chrome on iOS. 

Do you have plans to integrate push notification functionality from the magento back end as part of this extension?

Happy also to contribute financially if you have the option for me to do that as a gesture of thanks for the extension. 

Pete

**Comment by bobbyshaw** [comment]
We've looked at it briefly but it's been low on the list at the moment. We'll certainly be considering it but it'll likely be focussed on Magento 2.
