### ISSUE TITLE
Unsupported MIME type

### ISSUE THREAD

**Issue by alwaysriding1** [meanbee/magento-meanbee-pwa#7]
Hi Guys,

Bit of a strange one - this was working great, then Chrome started to report the below:

Failed to load resource: net::ERR_INSECURE_RESPONSE
Service worker registration failed: DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').

Any ideas why this might have occurred?

As you can see from our site, registration is failing consistently. 

Pete

**Comment by alwaysriding1** [comment]
Fixed - related to using Sucuri firewall and hardcore caching of js files - forced cache refresh and all now fine. Sorry.

**Comment by tgerulaitis** [comment]
No worries, Pete. Glad it's fixed!
