### ISSUE TITLE
Magento 2 Support

### ISSUE THREAD

**Issue by ahumphreys87** [meanbee/magento-meanbee-pwa#8]
Hi, this extension looks great - really keen to use it. Any plans for a Magento 2 version?

**Comment by punkstar** [comment]
Yup! I'd recommend signing up to our newsletter on https://meanbee.com as that's where we'd announce.

**Comment by bobbyshaw** [comment]
There is a service worker extension for Magento 2 that you can check out: https://github.com/meanbee/magento2-serviceworker

**Comment by ahumphreys87** [comment]
Thanks @punkstar, I've signed up.

Thanks @bobbyshaw, yup noticed the service worker extension after posting this issue, also noticed there is a web app manifest one as well. Good stuff!
